Repository kyupid/issue-tracker, pull requests merged in 2021-07, with the labels that each got.

#133 Kyu/feature/emoji 완성
  be/src/main/java/com/issuetracker/controller/EmojiController.java
  be/src/main/java/com/issuetracker/dto/EmojiRequestDto.java
  be/src/main/java/com/issuetracker/repository/EmojisStatusRepository.java
  be/src/main/java/com/issuetracker/service/EmojisStatusService.java
  be/src/main/resources/schema.sql
Labels: BE

#134 [#126] 코멘트 편집 기능
  fe/src/components/issue-detail/Comment.tsx
  fe/src/components/issue-detail/CommentEdit.tsx
Labels: FE, feature

#135 [#82] Feat & Fix: 이슈 상세 페이지에 사이드바 렌더링
  fe/src/components/issue-detail/IssueDetailBody.tsx
  fe/src/pages/NewIssuePage.tsx
Labels: FE, feature

#137 [#82] Feat: 이슈 닫기, 다시 열기 기능 추가
  fe/src/components/issue-detail/IssueDetailHeader.tsx
  fe/src/stores/detailIssueStore.ts
  fe/src/stores/issueStore.ts
Labels: FE, feature

#139 [#82] Feat: 이슈 삭제 기능 추가
  fe/src/components/issue-detail/IssueDetailBody.tsx
Labels: FE, feature

#138 [BE] 리팩토링용 PR
  be/src/main/java/com/issuetracker/config/CorsFilter.java
  be/src/main/java/com/issuetracker/controller/IssueController.java
  be/src/main/java/com/issuetracker/dto/LabelForIssueDetailDto.java
  be/src/main/java/com/issuetracker/dto/MilestoneForIssueDetailDto.java
  be/src/main/java/com/issuetracker/oauth/LoginController.java
  be/src/main/java/com/issuetracker/repository/IssueRepository.java
  be/src/main/java/com/issuetracker/repository/UserRepository.java
  be/src/main/java/com/issuetracker/s3/ImageService.java
  be/src/main/java/com/issuetracker/s3/ImageUrlResponseDto.java
  be/src/main/java/com/issuetracker/s3/UploadController.java
  be/src/main/java/com/issuetracker/service/EmojisStatusService.java
  be/src/main/java/com/issuetracker/service/IssueService.java
  be/src/main/java/com/issuetracker/util/Oauth.java
Labels: BE

#143 [#140][#116] Fix: 버그 해결
  fe/src/components/common/FilterItem.tsx
  fe/src/components/milestones/MilestoneBar.tsx
  fe/src/components/milestones/MilestonesItemRight.tsx
  fe/src/components/new-issue/NewIssueLeft.tsx
  fe/src/components/new-issue/SidebarList.tsx
  fe/src/hook/useAxios.tsx
  fe/src/pages/NewIssuePage.tsx
  fe/src/pages/OAuthPage.tsx
  fe/src/stores/issueStore.ts
Labels: FE, bug

#144 [#142] 로그아웃 버튼 스타일링, 이슈 목록 헤더의 필터 버튼들 수정
  fe/src/components/Issues/IssuesHeader.tsx
  fe/src/components/header/Header.tsx
  fe/src/types/filterType.ts
Labels: FE, UI
