Repository kyupid/issue-tracker, pull requests merged in 2021-06, with the labels that each got.

#17 [#9] Fix: Styled Component가 Material UI를 override하도록 설정
  fe/src/index.tsx
  fe/src/style/GlobalStyle.tsx
  fe/src/style/theme.ts
Labels: FE, enhancement

#20 Oauth 통한 JWT 발급 그리고 Interceptor 구현
  be/src/main/java/com/issuetracker/config/InterceptorConfig.java
  be/src/main/java/com/issuetracker/oauth/LoginController.java
  be/src/main/java/com/issuetracker/oauth/OauthInterceptor.java
  be/src/main/java/com/issuetracker/oauth/User.java
  be/src/main/java/com/issuetracker/util/Oauth.java
Labels: BE, feature

#22 [FE] 필터 UI를 공통 컴포넌트로 만들기 위한 작업, 리팩토링
  fe/package-lock.json
  fe/package.json
  fe/src/components/common/FilterItem.tsx
  fe/src/components/common/FilterList.tsx
  fe/src/components/common/IssueFilter.tsx
  fe/src/components/navbar/Navbar.tsx
  fe/src/pages/IssuesPage.tsx
  fe/src/types/filterType.ts
  fe/yarn.lock
Labels: FE, feature, refactor

#29 [#27] 이슈 전체 조회 API 구현을 위한 테스트
  be/build.gradle
  be/src/main/java/com/issuetracker/controller/IssueController.java
  be/src/main/java/com/issuetracker/controller/IssueDto.java
  be/src/main/java/com/issuetracker/domain/Issue.java
  be/src/main/java/com/issuetracker/domain/Label.java
  be/src/main/java/com/issuetracker/repository/IssueMapper.java
  be/src/main/java/com/issuetracker/repository/IssueRepository.java
  be/src/main/java/com/issuetracker/service/IssueService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  be/src/test/java/com/issuetracker/repository/IssueRepositoryTests.java
Labels: BE, feature

#33 [FE] navbar 오른쪽 UI 작업
  fe/src/components/navbar/Navbar.tsx
  fe/src/style/GlobalStyle.tsx
  fe/src/style/theme.ts
Labels: FE, UI

#38 [#37] Feat: 서버에서 filter list 받아서 화면에 표시
  fe/src/App.tsx
  fe/src/components/Issues/IssuesHeader.tsx
  fe/src/components/common/Filter.tsx
  fe/src/components/common/FilterItem.tsx
  fe/src/components/common/IssueFilter.tsx
  fe/src/store.ts
  fe/src/types/filterType.ts
Labels: FE, feature

#39 [#27] 이슈 전체 조회 API 구현
  be/.gitignore
  be/build.gradle
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/com/issuetracker/IssueTrackerApplication.java
  be/src/main/java/com/issuetracker/config/InterceptorConfig.java
  be/src/main/java/com/issuetracker/controller/IssueController.java
  be/src/main/java/com/issuetracker/controller/IssueDto.java
  be/src/main/java/com/issuetracker/domain/Issue.java
  be/src/main/java/com/issuetracker/domain/Label.java
  be/src/main/java/com/issuetracker/domain/Milestone.java
  be/src/main/java/com/issuetracker/dto/IssueDto.java
  be/src/main/java/com/issuetracker/oauth/User.java
  be/src/main/java/com/issuetracker/repository/IssueMapper.java
  be/src/main/java/com/issuetracker/repository/IssueRepository.java
  be/src/main/java/com/issuetracker/repository/LabelRepository.java
  be/src/main/java/com/issuetracker/repository/MilestoneRepository.java
  be/src/main/java/com/issuetracker/service/IssueService.java
  be/src/main/java/com/issuetracker/util/RowMappers.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  be/src/test/java/com/issuetracker/issue/IssueControllerTest.java
  be/src/test/java/com/issuetracker/issue/IssueRepositoryTests.java
  be/src/test/java/com/issuetracker/issue/IssueTestData.java
  be/src/test/java/com/issuetracker/repository/IssueRepositoryTests.java
Labels: BE, feature

#43 [#42] label list page & milestone Page
  fe/src/App.tsx
  fe/src/components/Issues/IssueItem.tsx
  fe/src/components/Issues/IssueItemLeft.tsx
  fe/src/components/Issues/Issues.tsx
  fe/src/components/Issues/IssuesHeader.tsx
  fe/src/components/buttons/CreateButton.tsx
  fe/src/components/buttons/CustomButton.tsx
  fe/src/components/common/CommentInput.tsx
  fe/src/components/common/CommentTextarea.tsx
  fe/src/components/common/Filter.tsx
  fe/src/components/common/FilterItem.tsx
  fe/src/components/common/FilterList.tsx
  fe/src/components/common/IssueFilter.tsx
  fe/src/components/common/Table.tsx
  fe/src/components/labels/Labels.tsx
  fe/src/components/labels/LabelsItem.tsx
  fe/src/components/labels/LabelsItemLeft.tsx
  fe/src/components/labels/LabelsItemRight.tsx
  fe/src/components/milestones/MilestoneBar.tsx
  fe/src/components/milestones/Milestones.tsx
  fe/src/components/milestones/MilestonesItem.tsx
  fe/src/components/milestones/MilestonesItemLeft.tsx
  fe/src/components/milestones/MilestonesItemRight.tsx
  fe/src/components/navbar/Navbar.tsx
  fe/src/components/navbar/NavbarButtons.tsx
  fe/src/components/new-issue/NewIssueLeft.tsx
  fe/src/components/new-issue/NewIssueRight.tsx
  fe/src/components/new-issue/SidebarList.tsx
  fe/src/hook/useAxios.tsx
  fe/src/icons/calendar.svg
  fe/src/icons/milestoneBlue.svg
  fe/src/pages/LabelPage.tsx
  fe/src/pages/MilestoneListPage.tsx
  fe/src/pages/NewIssuePage.tsx
  fe/src/pages/OAuthPage.tsx
  fe/src/types/filterType.ts
  fe/src/types/issueType.ts
  fe/src/types/newIssueType.ts
  fe/src/utils/util.ts
Labels: FE

#44 [FE] 이슈 상세 페이지 UI 작업 (오른쪽 사이드바 제외)
  fe/src/App.tsx
  fe/src/components/issue-detail/Comment.tsx
  fe/src/components/issue-detail/IssueDetailBody.tsx
  fe/src/components/issue-detail/IssueDetailHeader.tsx
  fe/src/components/issue-detail/IssueStateSign.tsx
  fe/src/pages/IssueDetailPage.tsx
Labels: FE, UI

#45 [FE] 이슈 상세 페이지 0번째 comment margin값 수정, 새 코멘트 ui 추가
  fe/src/components/common/CommentTextarea.tsx
  fe/src/components/issue-detail/IssueDetailBody.tsx
  fe/src/components/new-issue/NewIssueRight.tsx
Labels: FE, UI

#53 [FE] 라벨 목록 페이지 - 서버로부터 받은 데이터를 상태에 저장하여 렌더링하도록 수정
  fe/src/components/Issues/IssueItemLeft.tsx
  fe/src/components/common/FilterItem.tsx
  fe/src/components/common/IssueFilter.tsx
  fe/src/components/common/Label.tsx
  fe/src/components/labels/Labels.tsx
  fe/src/components/labels/LabelsItem.tsx
  fe/src/components/labels/LabelsItemLeft.tsx
  fe/src/pages/IssuesPage.tsx
  fe/src/pages/LabelPage.tsx
  fe/src/pages/MilestoneListPage.tsx
  fe/src/store.ts
  fe/src/types/filterType.ts
Labels: FE, UI, feature

#55 [FE] Refactor: 코드리뷰 일부 반영, 타입선언 파일 분리, 자잘한 오타 수정
  fe/src/components/Issues/IssueItemLeft.tsx
  fe/src/components/Issues/IssueList.tsx
  fe/src/components/buttons/CreateButton.tsx
  fe/src/components/common/Filter.tsx
  fe/src/components/common/Label.tsx
  fe/src/components/labels/Labels.tsx
  fe/src/components/labels/LabelsItem.tsx
  fe/src/components/labels/LabelsItemLeft.tsx
  fe/src/components/new-issue/SidebarList.tsx
  fe/src/icons/plus.svg
  fe/src/store.ts
  fe/src/types/filterType.ts
  fe/src/types/issueType.ts
  fe/src/types/storeTypes.ts
Labels: FE, refactor

#62 [BE] 이슈 생성/검색 API
  be/.gitignore
  be/src/main/java/com/issuetracker/config/CorsFilter.java
  be/src/main/java/com/issuetracker/config/InterceptorConfig.java
  be/src/main/java/com/issuetracker/controller/IssueController.java
  be/src/main/java/com/issuetracker/domain/Issue.java
  be/src/main/java/com/issuetracker/domain/Label.java
  be/src/main/java/com/issuetracker/dto/IssueDto.java
  be/src/main/java/com/issuetracker/dto/IssueRequestDto.java
  be/src/main/java/com/issuetracker/dto/IssueSearchCondition.java
  be/src/main/java/com/issuetracker/dto/ResponseStatusDto.java
  be/src/main/java/com/issuetracker/oauth/LoginController.java
  be/src/main/java/com/issuetracker/oauth/User.java
  be/src/main/java/com/issuetracker/repository/IssueRepository.java
  be/src/main/java/com/issuetracker/repository/LabelRepository.java
  be/src/main/java/com/issuetracker/repository/UserRepository.java
  be/src/main/java/com/issuetracker/service/IssueService.java
  be/src/main/java/com/issuetracker/util/Oauth.java
  be/src/main/java/com/issuetracker/util/RowMappers.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  be/src/test/java/com/issuetracker/issue/IssueControllerTest.java
  be/src/test/java/com/issuetracker/issue/IssueRepositoryTests.java
  be/src/test/java/com/issuetracker/issue/IssueTestData.java
Labels: BE, feature

#70 Feat: 마일스톤 closed 조건에 따른 전체 조회 API
  be/src/main/java/com/issuetracker/controller/MilestoneController.java
  be/src/main/java/com/issuetracker/repository/MilestoneRepository.java
  be/src/main/java/com/issuetracker/service/MilestoneService.java
Labels: BE, feature

#71 [BE] 라벨 전체조회/생성/수정/삭제 API 구현
  be/src/main/java/com/issuetracker/config/InterceptorConfig.java
  be/src/main/java/com/issuetracker/controller/LabelController.java
  be/src/main/java/com/issuetracker/dto/LabelDto.java
  be/src/main/java/com/issuetracker/repository/IssueRepository.java
  be/src/main/java/com/issuetracker/repository/LabelRepository.java
  be/src/main/java/com/issuetracker/service/LabelService.java
  be/src/main/resources/schema.sql
Labels: BE, feature

#74 [#73] 서버에 보내는 요청 에러 해결
  fe/src/Router.tsx
  fe/src/components/buttons/GitHubLoginButton.tsx
  fe/src/pages/OAuthPage.tsx
  fe/src/store.ts
  fe/src/utils/util.ts
Labels: FE, bug

#76 [#75] Feat: jwt 토큰 유무 체크하여 로그인 페이지 또는 이슈 목록 페이지 렌더링
  fe/src/Router.tsx
  fe/src/pages/LoginPage.tsx
Labels: FE, feature

#80 [FE] 마일스톤 페이지 API 이용하여 렌더링
  fe/src/components/milestones/MilestoneBar.tsx
  fe/src/components/milestones/Milestones.tsx
  fe/src/components/milestones/MilestonesItemRight.tsx
  fe/src/components/milestones/MilestonesList.tsx
  fe/src/components/navbar/NavbarButtons.tsx
  fe/src/store.ts
  fe/src/stores/milestoneStore.ts
Labels: FE, feature

#87 Kyu/temp
  be/src/main/java/com/issuetracker/controller/Controller.java
  be/src/main/java/com/issuetracker/controller/MilestoneController.java
  be/src/main/java/com/issuetracker/dto/MilestoneCountDto.java
  be/src/main/java/com/issuetracker/oauth/LoginController.java
  be/src/main/java/com/issuetracker/oauth/User.java
  be/src/main/java/com/issuetracker/oauth/UserDto.java
  be/src/main/java/com/issuetracker/repository/MilestoneRepository.java
  be/src/main/java/com/issuetracker/repository/UserRepository.java
  be/src/main/java/com/issuetracker/service/MilestoneService.java
  be/src/main/java/com/issuetracker/service/Service.java
Labels: BE

#88 Be/feat comment
  be/src/main/java/com/issuetracker/controller/CommentController.java
  be/src/main/java/com/issuetracker/controller/LabelController.java
  be/src/main/java/com/issuetracker/controller/MilestoneController.java
  be/src/main/java/com/issuetracker/domain/Comment.java
  be/src/main/java/com/issuetracker/dto/CommentDto.java
  be/src/main/java/com/issuetracker/dto/CommentRequestDto.java
  be/src/main/java/com/issuetracker/repository/CommentRepository.java
  be/src/main/java/com/issuetracker/service/CommentService.java
  be/src/main/java/com/issuetracker/util/RowMappers.java
  be/src/main/resources/data.sql
Labels: BE

#90 [#82] Feat: 이슈 목록에서 이슈 클릭 시 상세 페이지로 라우팅
  fe/src/Router.tsx
  fe/src/components/Issues/IssueItem.tsx
  fe/src/components/Issues/IssueItemLeft.tsx
  fe/src/store.ts
  fe/src/types/issueType.ts
Labels: FE, feature

#92 [#52] Refactor: type 중복 제거 및 정리
  fe/src/components/common/Label.tsx
  fe/src/components/labels/LabelsItem.tsx
  fe/src/components/labels/LabelsItemLeft.tsx
  fe/src/components/milestones/MilestoneBar.tsx
  fe/src/components/milestones/MilestonesItemRight.tsx
  fe/src/components/new-issue/SidebarList.tsx
  fe/src/store.ts
  fe/src/types/issueType.ts
  fe/src/types/newIssueType.ts
  fe/src/types/storeTypes.ts
  fe/src/utils/util.ts
Labels: FE, refactor

#95 [#51][#52][#75][#94] jwt 토큰 디코딩
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/Router.tsx
  fe/src/components/common/Logo.tsx
  fe/src/components/header/Header.tsx
  fe/src/pages/IssuesPage.tsx
  fe/src/pages/OAuthPage.tsx
  fe/src/store.ts
  fe/src/stores/milestoneStore.ts
  fe/src/types/storeTypes.ts
  fe/yarn.lock
Labels: FE, bug, feature

#110 [#82] 이슈 상세 페이지 렌더링
  fe/src/components/Issues/IssueItem.tsx
  fe/src/components/Issues/IssueItemLeft.tsx
  fe/src/components/common/AuthorAvatar.tsx
  fe/src/components/header/Header.tsx
  fe/src/components/issue-detail/Comment.tsx
  fe/src/components/issue-detail/IssueDetailBody.tsx
  fe/src/components/issue-detail/IssueDetailHeader.tsx
  fe/src/components/issue-detail/IssueStateSign.tsx
  fe/src/components/new-issue/NewIssueLeft.tsx
  fe/src/pages/IssueDetailPage.tsx
  fe/src/store.ts
  fe/src/types/issueType.ts
  fe/src/types/storeTypes.ts
Labels: FE, feature

#114 [BE] [#113] Feat: 이미지 업로드 API
  be/build.gradle
  be/src/main/java/com/issuetracker/s3/ImageService.java
  be/src/main/java/com/issuetracker/s3/UploadController.java
Labels: BE

#117 [#111] 코멘트 작성 기능
  fe/src/components/buttons/CreateButton.tsx
  fe/src/components/common/CommentTextarea.tsx
  fe/src/components/issue-detail/Comment.tsx
  fe/src/components/issue-detail/IssueDetailBody.tsx
  fe/src/components/issue-detail/IssueDetailHeader.tsx
  fe/src/components/new-issue/NewIssueLeft.tsx
  fe/src/pages/IssueDetailPage.tsx
  fe/src/store.ts
  fe/src/stores/detailIssueStore.ts
Labels: FE, feature

#119 [#93][#118] 화면 렌더링 문제 해결
  fe/src/components/Issues/IssueItemLeft.tsx
  fe/src/components/issue-detail/Comment.tsx
  fe/src/stores/detailIssueStore.ts
Labels: FE, bug

#123 [#52] Refactor: store.ts 분리
  fe/src/components/Issues/IssueItemLeft.tsx
  fe/src/components/Issues/IssueList.tsx
  fe/src/components/Issues/IssuesHeader.tsx
  fe/src/components/common/CommentTextarea.tsx
  fe/src/components/common/Filter.tsx
  fe/src/components/header/Header.tsx
  fe/src/components/issue-detail/Comment.tsx
  fe/src/components/issue-detail/IssueDetailBody.tsx
  fe/src/components/labels/Labels.tsx
  fe/src/components/labels/LabelsItemInput.tsx
  fe/src/components/labels/LabelsItemRight.tsx
  fe/src/components/labels/NewLabelsItemInput.tsx
  fe/src/components/milestones/NewMilestone.tsx
  fe/src/components/navbar/NavbarButtons.tsx
  fe/src/components/new-issue/NewIssueLeft.tsx
  fe/src/components/new-issue/NewIssueRight.tsx
  fe/src/pages/IssuesPage.tsx
  fe/src/pages/NewIssuePage.tsx
  fe/src/store.ts
  fe/src/stores/NewIssuesSideStore.ts
  fe/src/stores/detailIssueStore.ts
  fe/src/stores/filterStore.ts
  fe/src/stores/issueStore.ts
  fe/src/stores/labelStore.ts
  fe/src/stores/userStore.ts
  fe/src/types/storeTypes.ts
  fe/src/utils/util.ts
Labels: FE, refactor

#129 Feat: 이모지 상태 전체 조회
  be/src/main/java/com/issuetracker/controller/EmojiController.java
  be/src/main/java/com/issuetracker/domain/SelectedEmoji.java
  be/src/main/java/com/issuetracker/dto/EmojisStatusDto.java
  be/src/main/java/com/issuetracker/repository/EmojisStatusRepository.java
  be/src/main/java/com/issuetracker/service/EmojisStatusService.java
  be/src/main/java/com/issuetracker/util/RowMappers.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE

#130 [#126] 코멘트 삭제 기능
  fe/src/components/issue-detail/Comment.tsx
  fe/src/components/issue-detail/IssueDetailBody.tsx
  fe/src/stores/detailIssueStore.ts
Labels: FE, feature
